/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.PerformanceReportsWorkResp;

import Business.Business;
import Business.Course.CourseOffer;
import Business.Course.SeatAssignment;
import Business.Profiles.FacultyProfile;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Panel for faculty to view performance reports for their courses
 * @author cohenpowell
 */
public class PerformanceReportsJPanel extends javax.swing.JPanel {

    private Business business;
    private FacultyProfile facultyprofile;
    private JPanel CardSequencePanel;
    private ArrayList<CourseOffer> facultyCourses;

    // creates the performance reports panel for the logged-in faculty
    public PerformanceReportsJPanel(Business b, FacultyProfile fp, JPanel clp) {
        this.business = b;
        this.facultyprofile = fp;
        this.CardSequencePanel = clp;
        this.facultyCourses = new ArrayList();
        initComponents();
        loadFacultyCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        courseCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        lblAvgGrade = new javax.swing.JLabel();
        lblTotalStudents = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Performance Reports");
        add(jLabel1);
        jLabel1.setBounds(30, 10, 350, 28);

        jLabel2.setText("Select Course:");
        add(jLabel2);
        jLabel2.setBounds(30, 60, 120, 25);

        courseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboActionPerformed(evt);
            }
        });
        add(courseCombo);
        courseCombo.setBounds(150, 60, 300, 25);

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Grade", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reportTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 500, 200);

        lblAvgGrade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAvgGrade.setText("Class Average: N/A");
        add(lblAvgGrade);
        lblAvgGrade.setBounds(30, 330, 300, 25);

        lblTotalStudents.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTotalStudents.setText("Total Students: 0");
        add(lblTotalStudents);
        lblTotalStudents.setBounds(30, 360, 300, 25);

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(30, 400, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void courseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboActionPerformed
        loadReport();
    }//GEN-LAST:event_courseComboActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_backBtnActionPerformed

    // loads courses this faculty teaches into the dropdown
    private void loadFacultyCourses() {
        courseCombo.removeAllItems();
        facultyCourses.clear();

        for (CourseOffer co : business.getCourseSchedule().getCourseoffers()) {
            courseCombo.addItem(co.getCourse().toString() + " (" + co.getSemester() + ")");
            facultyCourses.add(co);
        }

        if (courseCombo.getItemCount() > 0) {
            courseCombo.setSelectedIndex(0);
            loadReport();
        }
    }

    // loads the performance report for the selected course
    private void loadReport() {
        DefaultTableModel model = (DefaultTableModel) reportTable.getModel();
        model.setRowCount(0);
        int index = courseCombo.getSelectedIndex();
        if (index < 0 || index >= facultyCourses.size()) return;

        CourseOffer selected = facultyCourses.get(index);
        int totalStudents = selected.getSeatassignments().size();
        double gradePoints = 0;
        int gradedCount = 0;

        for (SeatAssignment sa : selected.getSeatassignments()) {
            String name = sa.getStudent().getPersonId();
            String grade = sa.getGrade();
            // determine pass/fail/pending status
            String status = getStatus(grade);
            model.addRow(new Object[]{name, grade, status});

            // calculate grade points for average
            double pts = convertGradeToPoints(grade);
            if (pts >= 0) {
                gradePoints += pts;
                gradedCount++;
            }
        }

        lblTotalStudents.setText("Total Students: " + totalStudents);

        if (gradedCount > 0) {
            double avg = gradePoints / gradedCount;
            lblAvgGrade.setText("Class Average: " + String.format("%.2f", avg) + " GPA");
        } else {
            lblAvgGrade.setText("Class Average: N/A");
        }
    }

    // returns pass, fail, or pending based on grade
    private String getStatus(String grade) {
        if (grade == null || grade.equals("N/A")) return "Pending";
        if (grade.equals("F")) return "Fail";
        return "Pass";
    }

    // converts letter grade to GPA points
    private double convertGradeToPoints(String grade) {
        if (grade == null || grade.equals("N/A")) return -1;
        switch (grade) {
            case "A+": return 4.0;
            case "A": return 4.0;
            case "A-": return 3.7;
            case "B+": return 3.3;
            case "B": return 3.0;
            case "B-": return 2.7;
            case "C+": return 2.3;
            case "C": return 2.0;
            case "C-": return 1.7;
            case "D": return 1.0;
            case "F": return 0.0;
            default: return -1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvgGrade;
    private javax.swing.JLabel lblTotalStudents;
    private javax.swing.JTable reportTable;
    // End of variables declaration//GEN-END:variables
}
