/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.ManageStudentsWorkResp;

import Business.Business;
import Business.Course.CourseOffer;
import Business.Course.SeatAssignment;
import Business.Profiles.FacultyProfile;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Panel for faculty to view student profiles enrolled in their courses
 * @author cohenpowell
 */
public class ManageStudentProfilesJPanel extends javax.swing.JPanel {

    private Business business;
    private FacultyProfile facultyprofile;
    private JPanel CardSequencePanel;
    private ArrayList<CourseOffer> facultyCourses;

    // creates the manage student profiles panel for the logged-in faculty
    public ManageStudentProfilesJPanel(Business b, FacultyProfile fp, JPanel clp) {
        this.business = b;
        this.facultyprofile = fp;
        this.CardSequencePanel = clp;
        this.facultyCourses = new ArrayList();
        initComponents();
        loadFacultyCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        courseCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        lblDetails = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Manage Student Profiles");
        add(jLabel1);
        jLabel1.setBounds(30, 10, 400, 28);

        jLabel2.setText("Select Course:");
        add(jLabel2);
        jLabel2.setBounds(30, 60, 120, 25);

        courseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboActionPerformed(evt);
            }
        });
        add(courseCombo);
        courseCombo.setBounds(150, 60, 300, 25);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Grade", "Courses Enrolled"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 500, 200);

        lblDetails.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDetails.setText("Select a student to view details");
        add(lblDetails);
        lblDetails.setBounds(30, 330, 500, 25);

        viewBtn.setText("View Details");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        add(viewBtn);
        viewBtn.setBounds(30, 370, 120, 23);

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(30, 410, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void courseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboActionPerformed
        loadStudentsForCourse();
    }//GEN-LAST:event_courseComboActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        viewStudentDetails();
    }//GEN-LAST:event_viewBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_backBtnActionPerformed

    // loads courses into the dropdown
    private void loadFacultyCourses() {
        courseCombo.removeAllItems();
        facultyCourses.clear();

        for (CourseOffer co : business.getCourseSchedule().getCourseoffers()) {
            courseCombo.addItem(co.getCourse().toString() + " (" + co.getSemester() + ")");
            facultyCourses.add(co);
        }

        if (courseCombo.getItemCount() > 0) {
            courseCombo.setSelectedIndex(0);
            loadStudentsForCourse();
        }
    }

    // loads students enrolled in the selected course
    private void loadStudentsForCourse() {
        DefaultTableModel model = (DefaultTableModel) studentTable.getModel();
        model.setRowCount(0);
        int index = courseCombo.getSelectedIndex();
        if (index < 0 || index >= facultyCourses.size()) return;

        CourseOffer selected = facultyCourses.get(index);
        for (SeatAssignment sa : selected.getSeatassignments()) {
            String name = sa.getStudent().getPersonId();
            String grade = sa.getGrade();
            // count how many courses this student is enrolled in across the schedule
            int courseCount = countStudentCourses(sa.getStudent().getPersonId());
            model.addRow(new Object[]{name, grade, courseCount});
        }
    }

    // counts total courses a student is enrolled in
    private int countStudentCourses(String studentId) {
        int count = 0;
        for (CourseOffer co : business.getCourseSchedule().getCourseoffers()) {
            for (SeatAssignment sa : co.getSeatassignments()) {
                if (sa.getStudent().getPersonId().equals(studentId)) {
                    count++;
                }
            }
        }
        return count;
    }

    // shows details for the selected student
    private void viewStudentDetails() {
        int selectedRow = studentTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a student first.");
            return;
        }

        int courseIndex = courseCombo.getSelectedIndex();
        if (courseIndex < 0) return;

        CourseOffer selected = facultyCourses.get(courseIndex);
        SeatAssignment sa = selected.getSeatassignments().get(selectedRow);
        String studentName = sa.getStudent().getPersonId();

        // build a summary of all courses and grades for this student
        StringBuilder details = new StringBuilder();
        details.append("Student: ").append(studentName).append("\n\n");
        details.append("Enrolled Courses:\n");

        for (CourseOffer co : business.getCourseSchedule().getCourseoffers()) {
            for (SeatAssignment s : co.getSeatassignments()) {
                if (s.getStudent().getPersonId().equals(studentName)) {
                    details.append("  - ").append(co.getCourse().toString())
                           .append(" | Grade: ").append(s.getGrade()).append("\n");
                }
            }
        }

        JOptionPane.showMessageDialog(this, details.toString(), "Student Details", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
