/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.ManageCourseWorkResp;

import Business.Business;
import Business.Course.Course;
import Business.Course.CourseOffer;
import Business.Course.SeatAssignment;
import Business.Profiles.FacultyProfile;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * Panel for faculty to view their courses and manage student grades
 * @author cohenpowell
 */
public class ManageCoursesJPanel extends javax.swing.JPanel {

    private Business business;
    private FacultyProfile facultyprofile;
    private JPanel CardSequencePanel;
    private ArrayList<CourseOffer> facultyCourses;

    // creates the manage courses panel for the logged-in faculty
    public ManageCoursesJPanel(Business b, FacultyProfile fp, JPanel clp) {
        this.business = b;
        this.facultyprofile = fp;
        this.CardSequencePanel = clp;
        this.facultyCourses = new ArrayList();
        initComponents();
        loadFacultyCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        courseCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        gradeField = new javax.swing.JTextField();
        saveGradeBtn = new javax.swing.JButton();
        viewCourseDetailsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Manage Courses");
        add(jLabel1);
        jLabel1.setBounds(30, 10, 300, 28);

        jLabel2.setText("Select Course:");
        add(jLabel2);
        jLabel2.setBounds(30, 60, 120, 25);

        courseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboActionPerformed(evt);
            }
        });
        add(courseCombo);
        courseCombo.setBounds(150, 60, 300, 25);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 500, 250);

        jLabel3.setText("New Grade:");
        add(jLabel3);
        jLabel3.setBounds(30, 380, 100, 25);

        add(gradeField);
        gradeField.setBounds(130, 380, 100, 25);

        saveGradeBtn.setText("Save Grade");
        saveGradeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGradeBtnActionPerformed(evt);
            }
        });
        add(saveGradeBtn);
        saveGradeBtn.setBounds(250, 380, 120, 25);

        viewCourseDetailsBtn.setText("View/Edit Details");
        viewCourseDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCourseDetailsBtnActionPerformed(evt);
            }
        });
        add(viewCourseDetailsBtn);
        viewCourseDetailsBtn.setBounds(460, 60, 150, 25);

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(30, 420, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void courseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboActionPerformed
        loadStudentsForCourse();
    }//GEN-LAST:event_courseComboActionPerformed

    private void saveGradeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGradeBtnActionPerformed
        saveGrade();
    }//GEN-LAST:event_saveGradeBtnActionPerformed

    private void viewCourseDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCourseDetailsBtnActionPerformed
        viewAndEditCourseDetails();
    }//GEN-LAST:event_viewCourseDetailsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_backBtnActionPerformed

    // loads the courses this faculty member teaches
    private void loadFacultyCourses() {
        courseCombo.removeAllItems();
        facultyCourses.clear();

        // show all course offers for this semester
        for (CourseOffer co : business.getCourseSchedule().getCourseoffers()) {
            courseCombo.addItem(co.getCourse().toString() + " (" + co.getSemester() + ")");
            facultyCourses.add(co);
        }

        if (courseCombo.getItemCount() > 0) {
            courseCombo.setSelectedIndex(0);
            loadStudentsForCourse();
        }
    }

    // loads enrolled students for the selected course
    private void loadStudentsForCourse() {
        DefaultTableModel model = (DefaultTableModel) studentTable.getModel();
        model.setRowCount(0);
        int index = courseCombo.getSelectedIndex();
        if (index < 0 || index >= facultyCourses.size()) return;

        CourseOffer selected = facultyCourses.get(index);
        for (SeatAssignment sa : selected.getSeatassignments()) {
            String studentName = sa.getStudent().getPersonId();
            String grade = sa.getGrade();
            model.addRow(new Object[]{studentName, grade});
        }
    }

    // saves the grade for the selected student
    private void saveGrade() {
        int selectedRow = studentTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a student first.");
            return;
        }

        String newGrade = gradeField.getText().trim();
        if (newGrade.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a grade.");
            return;
        }

        int courseIndex = courseCombo.getSelectedIndex();
        if (courseIndex < 0) return;

        CourseOffer selected = facultyCourses.get(courseIndex);
        SeatAssignment sa = selected.getSeatassignments().get(selectedRow);
        sa.setGrade(newGrade);

        // refresh the table
        loadStudentsForCourse();
        gradeField.setText("");
        JOptionPane.showMessageDialog(this, "Grade saved successfully.");
    }

    // opens a dialog to view and edit the selected course details
    private void viewAndEditCourseDetails() {
        int courseIndex = courseCombo.getSelectedIndex();
        if (courseIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a course first.");
            return;
        }

        CourseOffer selected = facultyCourses.get(courseIndex);
        Course course = selected.getCourse();

        // build an editable form using a panel with labels and text fields
        JTextField nameField = new JTextField(course.getCoursename(), 20);
        JTextField creditsField = new JTextField(String.valueOf(course.getCredits()), 5);
        JTextField descField = new JTextField(course.getDescription(), 30);

        JPanel editPanel = new JPanel();
        editPanel.setLayout(new java.awt.GridLayout(4, 2, 5, 5));
        editPanel.add(new JLabel("Course Number:"));
        editPanel.add(new JLabel(course.getCoursenumber())); // not editable
        editPanel.add(new JLabel("Course Name:"));
        editPanel.add(nameField);
        editPanel.add(new JLabel("Credits:"));
        editPanel.add(creditsField);
        editPanel.add(new JLabel("Description:"));
        editPanel.add(descField);

        int result = JOptionPane.showConfirmDialog(this, editPanel,
                "View / Edit Course Details", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            // update the course with new values
            String newName = nameField.getText().trim();
            String newCreditsStr = creditsField.getText().trim();
            String newDesc = descField.getText().trim();

            if (newName.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Course name cannot be empty.");
                return;
            }

            int newCredits;
            try {
                newCredits = Integer.parseInt(newCreditsStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Credits must be a number.");
                return;
            }

            course.setCoursename(newName);
            course.setCredits(newCredits);
            course.setDescription(newDesc);

            // refresh the dropdown to show updated name
            loadFacultyCourses();
            JOptionPane.showMessageDialog(this, "Course details updated successfully.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JTextField gradeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveGradeBtn;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton viewCourseDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
