/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.MyProfileWorkResp;

import Business.Business;
import Business.Profiles.FacultyProfile;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Panel for faculty to view and update their own profile info
 * @author cohenpowell
 */
public class FacultyMyProfileJPanel extends javax.swing.JPanel {

    private Business business;
    private FacultyProfile facultyprofile;
    private JPanel CardSequencePanel;

    // creates the my profile panel for the logged-in faculty
    public FacultyMyProfileJPanel(Business b, FacultyProfile fp, JPanel clp) {
        this.business = b;
        this.facultyprofile = fp;
        this.CardSequencePanel = clp;
        initComponents();
        loadProfileData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblRole = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        lblDept = new javax.swing.JLabel();
        txtDept = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("My Profile");
        add(jLabel1);
        jLabel1.setBounds(30, 10, 300, 28);

        lblName.setText("Name:");
        add(lblName);
        lblName.setBounds(30, 70, 100, 25);

        txtName.setEditable(false);
        add(txtName);
        txtName.setBounds(150, 70, 300, 25);

        lblRole.setText("Role:");
        add(lblRole);
        lblRole.setBounds(30, 110, 100, 25);

        txtRole.setEditable(false);
        add(txtRole);
        txtRole.setBounds(150, 110, 300, 25);

        lblDept.setText("Department:");
        add(lblDept);
        lblDept.setBounds(30, 150, 100, 25);

        add(txtDept);
        txtDept.setBounds(150, 150, 300, 25);

        lblEmail.setText("Email:");
        add(lblEmail);
        lblEmail.setBounds(30, 190, 100, 25);

        add(txtEmail);
        txtEmail.setBounds(150, 190, 300, 25);

        lblPhone.setText("Phone:");
        add(lblPhone);
        lblPhone.setBounds(30, 230, 100, 25);

        add(txtPhone);
        txtPhone.setBounds(150, 230, 300, 25);

        saveBtn.setText("Save Profile");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn);
        saveBtn.setBounds(150, 290, 120, 23);

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(30, 290, 80, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        saveProfile();
    }//GEN-LAST:event_saveBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_backBtnActionPerformed

    // loads the faculty member's current profile data into the fields
    private void loadProfileData() {
        txtName.setText(facultyprofile.getPerson().getPersonId());
        txtRole.setText(facultyprofile.getRole());
        txtDept.setText(facultyprofile.getDepartment());
        txtEmail.setText(facultyprofile.getEmail());
        txtPhone.setText(facultyprofile.getPhone());
    }

    // saves updated profile info with validation
    private void saveProfile() {
        String dept = txtDept.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();

        if (dept.isEmpty() && email.isEmpty() && phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in at least one field to update.");
            return;
        }

        // validate email format if provided
        if (!email.isEmpty() && !email.contains("@")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
            return;
        }

        // save to the faculty profile object so it persists
        facultyprofile.setDepartment(dept);
        facultyprofile.setEmail(email);
        facultyprofile.setPhone(phone);

        JOptionPane.showMessageDialog(this, "Profile updated successfully.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDept;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField txtDept;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRole;
    // End of variables declaration//GEN-END:variables
}
