/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.UserAccounts.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Detail panel for viewing and editing a selected user account.
 * @author fredtriest
 */

public class AdminUserAccount extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    UserAccount selecteduseraccount;
    Business business;
    ManageUserAccountsJPanel manageUserAccountsPanel;

    public AdminUserAccount(UserAccount sua, JPanel jp, Business bz, ManageUserAccountsJPanel muap) {

        CardSequencePanel = jp;
        selecteduseraccount= sua;
        business = bz;
        manageUserAccountsPanel = muap;
        initComponents();
        loadUser();

    }
    
    /**
     * Loads selected user details and validates the selected user is not null.
     */
    private void loadUser() {
        
        if (selecteduseraccount == null)
            return;
        
        txtUsername.setText(selecteduseraccount.getUserLoginName());
        txtName.setText(selecteduseraccount.getPersonId());
        txtRole.setText(selecteduseraccount.getRole());
        txtPassword.setText(selecteduseraccount.getPassword());
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        lblRole1 = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnUpdate.setText("Update>>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(480, 290, 100, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Administer User Account");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 290, 100, 23);

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("Password:");
        add(lblPassword);
        lblPassword.setBounds(120, 220, 70, 20);

        lblUsername1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername1.setText("Username:");
        add(lblUsername1);
        lblUsername1.setBounds(120, 100, 70, 20);

        lblName1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName1.setText("Name:");
        add(lblName1);
        lblName1.setBounds(120, 140, 70, 20);
        add(txtPassword);
        txtPassword.setBounds(210, 220, 190, 23);
        add(txtUsername);
        txtUsername.setBounds(210, 100, 190, 23);

        txtName.setEditable(false);
        add(txtName);
        txtName.setBounds(210, 140, 190, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(270, 340, 72, 23);

        lblRole1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblRole1.setForeground(new java.awt.Color(255, 255, 255));
        lblRole1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole1.setText("Role:");
        add(lblRole1);
        lblRole1.setBounds(120, 180, 70, 20);

        txtRole.setEditable(false);
        add(txtRole);
        txtRole.setBounds(210, 180, 190, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Validates and updates username and pw
        String newUsername = txtUsername.getText().trim();
        String newPassword = txtPassword.getText().trim();
        
        if (newUsername.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username can't be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // update username
        selecteduseraccount.setUserLoginName(newUsername);
        
        // update password
        if (!newPassword.isEmpty()) {
            selecteduseraccount.setPassword(newPassword);
        }
        
        JOptionPane.showMessageDialog(this, "User updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Go back to user list
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Returns to user accounts list
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Deletes the user confirmation
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this user?", "Confirm Delete",JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION)
        return;
        
        // Delete user
        business.getUserAccountDirectory().removeUserAccount(selecteduseraccount);
        manageUserAccountsPanel.refreshTable();;
        
        JOptionPane.showMessageDialog(this, "User deleted!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Back to user list
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
